#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Tue Sep 16 08:44:44 2003

from wxPython.wx import *

class CommandPanel(wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CommandPanel.__init__
        kwds["style"] = wxTAB_TRAVERSAL
        wxPanel.__init__(self, *args, **kwds)
        self.command_list = wxListCtrl(self, -1, style=wxLC_REPORT|wxSUNKEN_BORDER)
        self.label_command_name = wxStaticText(self, -1, "Command")
        self.label_replacement = wxStaticText(self, -1, "replacement")
        self.txt_command_name = wxTextCtrl(self, -1, "")
        self.txt_command_replacement = wxTextCtrl(self, -1, "")
        self.btn_add = wxButton(self, -1, "add")
        self.btn_delete = wxButton(self, -1, "delete")
        self.btn_close = wxButton(self, -1, "close")
        self.static_line_1 = wxStaticLine(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CommandPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CommandPanel.__do_layout
        vsizer = wxBoxSizer(wxVERTICAL)
        btn_sizer = wxBoxSizer(wxHORIZONTAL)
        text_sizer = wxBoxSizer(wxHORIZONTAL)
        label_sizer = wxBoxSizer(wxHORIZONTAL)
        vsizer.Add(self.command_list, 1, wxEXPAND, 0)
        label_sizer.Add(self.label_command_name, 1, wxEXPAND, 0)
        label_sizer.Add(self.label_replacement, 1, wxEXPAND, 0)
        vsizer.Add(label_sizer, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0)
        text_sizer.Add(self.txt_command_name, 1, wxEXPAND, 0)
        text_sizer.Add(self.txt_command_replacement, 1, wxEXPAND, 0)
        vsizer.Add(text_sizer, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0)
        btn_sizer.Add(self.btn_add, 1, wxEXPAND, 0)
        btn_sizer.Add(self.btn_delete, 1, wxEXPAND, 0)
        btn_sizer.Add(self.btn_close, 1, wxEXPAND, 0)
        vsizer.Add(btn_sizer, 0, wxEXPAND, 0)
        vsizer.Add(self.static_line_1, 0, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(vsizer)
        vsizer.Fit(self)
        vsizer.SetSizeHints(self)
        # end wxGlade

# end of class CommandPanel

class KeyPanel(wxPanel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: KeyPanel.__init__
        kwds["style"] = wxTAB_TRAVERSAL
        wxPanel.__init__(self, *args, **kwds)
        self.keybind_list = wxListCtrl(self, -1, style=wxLC_REPORT|wxSUNKEN_BORDER)
        self.label_keybind = wxStaticText(self, -1, "bind", style=wxALIGN_CENTRE)
        self.label_command = wxStaticText(self, -1, "command", style=wxALIGN_CENTRE)
        self.txt_keybind = wxTextCtrl(self, -1, "")
        self.txt_command = wxTextCtrl(self, -1, "")
        self.static_line = wxStaticLine(self, -1)
        self.btn_keybind_capture = wxButton(self, -1, "capture")
        self.btn_keybind_add = wxButton(self, -1, "add")
        self.btn_keybind_delete = wxButton(self, -1, "delete")
        self.btn_keybind_save = wxButton(self, -1, "save")
        self.btn_keybind_close = wxButton(self, -1, "close")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: KeyPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: KeyPanel.__do_layout
        vsizer = wxBoxSizer(wxVERTICAL)
        btn_sizer = wxBoxSizer(wxHORIZONTAL)
        text_sizer = wxBoxSizer(wxHORIZONTAL)
        label_sizer = wxBoxSizer(wxHORIZONTAL)
        vsizer.Add(self.keybind_list, 1, wxEXPAND, 0)
        label_sizer.Add(self.label_keybind, 1, wxEXPAND, 0)
        label_sizer.Add(self.label_command, 1, wxEXPAND, 0)
        vsizer.Add(label_sizer, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0)
        text_sizer.Add(self.txt_keybind, 1, 0, 0)
        text_sizer.Add(self.txt_command, 1, 0, 0)
        vsizer.Add(text_sizer, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0)
        vsizer.Add(self.static_line, 0, wxEXPAND, 0)
        btn_sizer.Add(self.btn_keybind_capture, 0, 0, 0)
        btn_sizer.Add(self.btn_keybind_add, 1, wxEXPAND, 0)
        btn_sizer.Add(self.btn_keybind_delete, 1, wxEXPAND, 0)
        btn_sizer.Add(self.btn_keybind_save, 1, wxEXPAND, 0)
        btn_sizer.Add(self.btn_keybind_close, 1, wxEXPAND, 0)
        vsizer.Add(btn_sizer, 0, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(vsizer)
        vsizer.Fit(self)
        vsizer.SetSizeHints(self)
        # end wxGlade

# end of class KeyPanel


